# ____ _____  _    ____  ____  _   _ ___ ____
#/ ___|_   _|/ \  |  _ \/ ___|| | | |_ _|  _ \
#\___ \ | | / _ \ | |_) \___ \| |_| || || |_) |
# ___) || |/ ___ \|  _ < ___) |  _  || ||  __/
#|____/ |_/_/   \_\_| \_\____/|_| |_|___|_|

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Use <format = "$all"> to display all modules
# $cmd_duration break bash DEBUG trap !
format = """
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$docker_context\
$package\
$dotnet\
$golang\
$nim\
$nodejs\
$perl\
$python\
$rust\
$memory_usage\
$env_var\
$custom\
$line_break\
$jobs\
$status\
$character"""

# Timeout for starship to scan files (in milliseconds)
scan_timeout = 10

# Timeout for commands executed by starship (in milliseconds)
command_timeout = 250

# Don't print a new line at the start of the prompt
add_newline = false

# MODULES

[aws]
disabled = true
symbol = "  "

[battery]
disabled = true

[buf]
disabled = true

[bun]
disabled = true

[c]
symbol = " "

[character]
error_symbol = "[](bold red) "
disabled = false
#success_symbol = "[](bold green) "

[cobol]
disabled = true

[conda]
disabled = true

[crystal]
disabled = true

[cmd_duration]
min_time = 5_000
show_milliseconds = true
show_notifications = false
min_time_to_notify = 120_000
disabled = true

[daml]
disabled = true

[deno]
disabled = true

[directory]
truncation_length = 2
format = "[$path]($style)[ $read_only]($read_only_style) "
style = "fg:bright-yellow"
fish_style_pwd_dir_length = 2
use_logical_path = true
disabled = false
read_only = " "

[docker_context]
only_with_files = true
disabled = false
symbol = " "

[dotnet]
disabled = true
heuristic = false

[env_var]
disabled = false

[fossil_branch]
symbol = " "

[git_branch]
disabled = false
symbol = " "

[git_commit]
disabled = false

[git_state]
disabled = false

[git_status]
disabled = false

[gcloud]
disabled = true

[golang]
disabled = true
symbol = " "

[haskell]
symbol = " "

[helm]
disabled = true

[hg_branch]
symbol = " "

[hostname]
disabled = false

[java]
disabled = true
symbol = " "

[jobs]
disabled = false

[julia]
disabled = true

[kubernetes]
disabled = true

[line_break]
disabled = true

[lua]
disabled = true
symbol = " "

[memory_usage]
threshold = 60
disabled = true
symbol = " "

[meson]
symbol = "喝 "

[nim]
disabled = false
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
disabled = false
symbol = " "

[ocaml]
disabled = true

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "﯑ "
Gentoo = " "
Illumos = " "
Linux = " "
Macos = " "
Manjaro = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
OracleLinux = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = "ﴱ "
SUSE = " "
Ubuntu = " "
Unknown = " "

[package]
display_private = true
disabled = true
symbol = " "

[perl]
disabled = true

[php]
disabled = true

[python]
disabled = false
symbol = " "

[ruby]
symbol = " "

[rust]
disabled = false
symbol = " "

[scala]
symbol = " "

[shlvl]
disabled = true

[status]
disabled = false

[time]
disabled = true

[username]
disabled = false
